# Generated by Django 4.1.1 on 2024-10-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='f_fabricacion2',
            new_name='f_fabricacion',
        ),
    ]
