# Generated by Django 5.1.1 on 2024-10-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_rename_id_laboratorio_lab_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='lab_ciudad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='lab_pais',
            field=models.CharField(max_length=255),
        ),
    ]
